sudo: false

language: rust

cache: 
  cargo: true
  directories:
    - integration_tests/target

rust:
  - stable

os:
  - linux
  - osx

matrix:
  include:
    - os: linux
      env: GNUPLOT=yes
      addons:
        apt:
          packages:
            - gnuplot
    - os: linux
      env: CLIPPY=yes
      rust: stable
    - os: linux
      env: RUSTFMT=yes
      rust: stable
    - os: linux
      env: GNUPLOT=yes
      rust: 1.40.0
      addons:
        apt:
          packages:
            - gnuplot
    - os: linux
      env: GNUPLOT=no
      rust: nightly
    - os: linux
      env: GNUPLOT=no
      rust: nightly
    - os: linux
      env: GNUPLOT=yes
      rust: nightly
      addons:
        apt:
          packages:
            - gnuplot
    - os: osx
      env: GNUPLOT=yes


install:
  - sh ci/install.sh

script:
  - sh ci/script.sh

before_cache:
- find ./target/debug -maxdepth 1 -type f -delete
- rm -rf ./target/debug/deps/*cargo*criterion*
- rm -rf ./target/debug/.fingerprint/*cargo*criterion*
- rm -f  ./target/.rustc_info.json
- find ./integration_tests/target/debug -maxdepth 1 -type f -delete
- find ./integration_tests/target/release -maxdepth 1 -type f -delete
- rm -rf ./integration_tests/target/debug/deps/test_benchmark*
- rm -rf ./integration_tests/target/debug/deps/integration_test*
- rm -rf ./integration_tests/target/debug/.fingerprint/test_benchmark*
- rm -rf ./integration_tests/target/debug/.fingerprint/integration_test*
- rm -rf ./integration_tests/target/release/deps/test_benchmark*
- rm -rf ./integration_tests/target/release/deps/integration_test*
- rm -rf ./integration_tests/target/release/.fingerprint/test_benchmark*
- rm -rf ./integration_tests/target/release/.fingerprint/integration_test*
- rm -f  ./integration_tests/target/.rustc_info.json

notifications:
  email:
    on_success: never
